version: "3.9"

services:
  staticserve:
    container_name: markdown_workspace_staticserve
    build:
      context: .
      dockerfile: staticserve/Dockerfile
    restart: unless-stopped
    networks:
      - dockerwp

networks:
  dockerwp:
    name: dockerwp
