packages:
  - "apps/*"
  - "packages/contracts/*"
  - "packages/renderer/*"
  - "packages/editor/*"
  - "packages/lander/*"
  - "packages/content/*"
  - "packages/extensions/*"
  - "packages/shared/*"
  - "examples/*"
