export const LANGUAGE_PACK_STUDIO_EXTENSION_ID = "core.language-pack-studio" as const;
export const LANGUAGE_PACK_STUDIO_VIEW_ID = `${LANGUAGE_PACK_STUDIO_EXTENSION_ID}.view` as const;
export const LANGUAGE_PACK_STUDIO_MODAL_VIEW_ID = `${LANGUAGE_PACK_STUDIO_EXTENSION_ID}.modal` as const;
export const LANGUAGE_PACK_STUDIO_COMMAND_ID = `${LANGUAGE_PACK_STUDIO_EXTENSION_ID}.open` as const;
export const LANGUAGE_PACK_STUDIO_MODAL_COMMAND_ID = `${LANGUAGE_PACK_STUDIO_EXTENSION_ID}.open-quick` as const;
export const LANGUAGE_PACK_STUDIO_RAIL_ID = `${LANGUAGE_PACK_STUDIO_EXTENSION_ID}.rail` as const;
