export const LANGUAGE_PACK_STUDIO_EXTENSION_ID = "core.language-pack-studio" as const;
export const LANGUAGE_PACK_STUDIO_VIEW_ID = `${LANGUAGE_PACK_STUDIO_EXTENSION_ID}.view` as const;
export const LANGUAGE_PACK_STUDIO_EXPLORER_VIEW_ID = `${LANGUAGE_PACK_STUDIO_EXTENSION_ID}.explorer` as const;
export const LANGUAGE_PACK_STUDIO_MODULE_ID = `${LANGUAGE_PACK_STUDIO_EXTENSION_ID}.module` as const;
export const LANGUAGE_PACK_STUDIO_COMMAND_ID = `${LANGUAGE_PACK_STUDIO_EXTENSION_ID}.open` as const;
export const LANGUAGE_PACK_STUDIO_RAIL_ID = `${LANGUAGE_PACK_STUDIO_EXTENSION_ID}.rail` as const;
