import React from 'react';
import type { ExtensionIcon } from '@mdwrk/extension-manifest';
import {
  AlertTriangle,
  ArrowRight,
  ArrowUpCircle,
  Book,
  Bot,
  Brush,
  CheckCircle,
  Cloud,
  CloudOff,
  Code,
  Columns,
  Command,
  Database,
  Download,
  Eye,
  FileDiff,
  FileDown,
  FilePlus,
  FileText,
  Folder,
  FolderPlus,
  GitBranch,
  Keyboard,
  Layout,
  LayoutGrid,
  Minus,
  Monitor,
  Moon,
  Palette,
  Pencil,
  Plug,
  Plus,
  Printer,
  Puzzle,
  RefreshCw,
  Save,
  Search,
  Settings,
  Sun,
  Terminal,
  Trash2,
  Upload,
  WifiOff,
  X,
  XCircle,
} from 'lucide-react';

const lucideCatalog: Record<string, React.ComponentType<{ size?: number; className?: string }>> = {
  AlertTriangle,
  ArrowRight,
  ArrowUpCircle,
  Book,
  Bot,
  Brush,
  CheckCircle,
  Cloud,
  CloudOff,
  Code,
  Columns,
  Command,
  Database,
  Download,
  Eye,
  FileDiff,
  FileDown,
  FilePlus,
  FileText,
  Folder,
  FolderPlus,
  GitBranch,
  Keyboard,
  Layout,
  LayoutGrid,
  Minus,
  Monitor,
  Moon,
  Palette,
  Pencil,
  Plug,
  Plus,
  Printer,
  Puzzle,
  RefreshCw,
  Save,
  Search,
  Settings,
  Sun,
  Terminal,
  Trash2,
  Upload,
  WifiOff,
  X,
  XCircle,
};

export function renderExtensionIcon(icon: ExtensionIcon | undefined, size = 16): React.ReactNode {
  if (!icon) return null;
  if (icon.kind === 'lucide') {
    const Component = lucideCatalog[icon.name] ?? Puzzle;
    return <Component size={size} />;
  }
  if (icon.kind === 'svg') {
    return <span aria-hidden="true" dangerouslySetInnerHTML={{ __html: icon.svg }} />;
  }
  return <Puzzle size={size} />;
}
