server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /client/versions/index.json {
    try_files $uri =404;
  }

  location ~ ^/client/versions/(?<version>[^/]+)/(.*)$ {
    try_files $uri $uri/ /client/versions/$version/index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
