import type { ExtensionManifest } from "@mdwrk/extension-manifest";
import {
  WORKSPACE_FILES_COMMAND_DELETE_ID,
  WORKSPACE_FILES_COMMAND_DOWNLOAD_WORKSPACE_ID,
  WORKSPACE_FILES_COMMAND_EXPORT_HTML_ID,
  WORKSPACE_FILES_COMMAND_FOCUS_EXPLORER_ID,
  WORKSPACE_FILES_COMMAND_IMPORT_MARKDOWN_ID,
  WORKSPACE_FILES_COMMAND_NEW_FILE_ID,
  WORKSPACE_FILES_COMMAND_NEW_FOLDER_ID,
  WORKSPACE_FILES_COMMAND_OPEN_HOST_FILE_ID,
  WORKSPACE_FILES_COMMAND_PRINT_PREVIEW_ID,
  WORKSPACE_FILES_COMMAND_RENAME_ID,
  WORKSPACE_FILES_COMMAND_SAVE_FILE_ID,
  WORKSPACE_FILES_COMMAND_TOGGLE_EXPLORER_ID,
  WORKSPACE_FILES_COMMAND_VIEW_EDITOR_ID,
  WORKSPACE_FILES_COMMAND_VIEW_PREVIEW_ID,
  WORKSPACE_FILES_COMMAND_VIEW_SPLIT_ID,
  WORKSPACE_FILES_EXPLORER_VIEW_ID,
  WORKSPACE_FILES_EXTENSION_ID,
  WORKSPACE_FILES_MODULE_ID,
  WORKSPACE_FILES_PRIMARY_VIEW_ID,
  WORKSPACE_FILES_RAIL_DOWNLOAD_ID,
  WORKSPACE_FILES_RAIL_IMPORT_MARKDOWN_ID,
  WORKSPACE_FILES_RAIL_NEW_FILE_ID,
  WORKSPACE_FILES_RAIL_NEW_FOLDER_ID,
  WORKSPACE_FILES_RAIL_OPEN_HOST_FILE_ID,
  WORKSPACE_FILES_RAIL_TOGGLE_EXPLORER_ID,
  WORKSPACE_FILES_SETTINGS_SECTION_ID,
} from "./constants.js";
import { WORKSPACE_FILES_VERSION } from "./version.js";

const label = (defaultMessage: string, key?: string) => ({ defaultMessage, key });

export const workspaceFilesManifest: ExtensionManifest = {
  manifestVersion: 1,
  id: WORKSPACE_FILES_EXTENSION_ID,
  packageName: "@mdwrk/extension-workspace-files",
  version: WORKSPACE_FILES_VERSION,
  displayName: label("Workspace Files"),
  description: label("First-party workspace module for file browsing, editing, previewing, import, and export actions."),
  kind: "bundled",
  icon: { kind: "lucide", name: "Folder" },
  enabledByDefault: true,
  capabilities: [
    "view.register",
    "actionRail.register",
    "settings.read",
    "settings.write",
    "notification.publish",
    "workspace.read",
    "workspace.write",
    "editor.read",
    "editor.write",
    "selection.read",
  ],
  capabilityPresetIds: ["workspace.module.writer"],
  compatibility: {
    manifestVersion: 1,
    hostApi: "^1.0.0",
    runtime: "^1.0.0",
    app: ">=1.4.21",
    themeContract: "^1.0.0",
    renderer: "^1.0.0",
    editor: "^1.0.0",
  },
  entry: {
    module: "./index.js",
    export: "createWorkspaceFilesBundledEntry",
  },
  i18n: {
    defaultLocale: "en",
    supportedLocales: ["en"],
  },
  contributions: {
    commands: [
      { id: WORKSPACE_FILES_COMMAND_TOGGLE_EXPLORER_ID, title: label("Toggle Explorer", "core.commands.toggle-explorer"), icon: { kind: "lucide", name: "Folder" } },
      { id: WORKSPACE_FILES_COMMAND_NEW_FILE_ID, title: label("Create New File", "core.commands.new-file"), icon: { kind: "lucide", name: "FilePlus" } },
      { id: WORKSPACE_FILES_COMMAND_NEW_FOLDER_ID, title: label("Create New Folder", "core.commands.new-folder"), icon: { kind: "lucide", name: "FolderPlus" } },
      { id: WORKSPACE_FILES_COMMAND_SAVE_FILE_ID, title: label("Save Current File", "core.commands.save-current-file"), icon: { kind: "lucide", name: "Save" } },
      { id: WORKSPACE_FILES_COMMAND_RENAME_ID, title: label("Rename Selected Item", "core.commands.rename-selected"), icon: { kind: "lucide", name: "Pencil" } },
      { id: WORKSPACE_FILES_COMMAND_DELETE_ID, title: label("Delete Selected Item", "core.commands.delete-selected"), icon: { kind: "lucide", name: "Trash2" } },
      { id: WORKSPACE_FILES_COMMAND_IMPORT_MARKDOWN_ID, title: label("Import Markdown", "core.import-markdown.title"), icon: { kind: "lucide", name: "Upload" } },
      { id: WORKSPACE_FILES_COMMAND_OPEN_HOST_FILE_ID, title: label("Open Markdown File", "core.commands.open-host-file"), icon: { kind: "lucide", name: "FolderOpen" } },
      { id: WORKSPACE_FILES_COMMAND_DOWNLOAD_WORKSPACE_ID, title: label("Download Workspace", "core.commands.download-workspace"), icon: { kind: "lucide", name: "Download" } },
      { id: WORKSPACE_FILES_COMMAND_EXPORT_HTML_ID, title: label("Export HTML", "core.commands.export-html"), icon: { kind: "lucide", name: "FileDown" } },
      { id: WORKSPACE_FILES_COMMAND_PRINT_PREVIEW_ID, title: label("Print Preview", "core.commands.print-preview"), icon: { kind: "lucide", name: "Printer" } },
      { id: WORKSPACE_FILES_COMMAND_VIEW_EDITOR_ID, title: label("Editor View", "core.commands.view-editor"), icon: { kind: "lucide", name: "LayoutGrid" } },
      { id: WORKSPACE_FILES_COMMAND_VIEW_SPLIT_ID, title: label("Split View", "core.commands.view-split"), icon: { kind: "lucide", name: "Columns" } },
      { id: WORKSPACE_FILES_COMMAND_VIEW_PREVIEW_ID, title: label("Preview View", "core.commands.view-preview"), icon: { kind: "lucide", name: "Eye" } },
      { id: WORKSPACE_FILES_COMMAND_FOCUS_EXPLORER_ID, title: label("Focus Explorer", "core.commands.focus-explorer"), icon: { kind: "lucide", name: "Folder" } },
    ],
    views: [
      {
        id: WORKSPACE_FILES_PRIMARY_VIEW_ID,
        title: label("Workspace Files"),
        description: label("File browsing, editing, and preview workspace."),
        icon: { kind: "lucide", name: "Folder" },
        location: "main",
        allowMultiple: false,
        canBePinned: true,
      },
      {
        id: WORKSPACE_FILES_EXPLORER_VIEW_ID,
        title: label("File Explorer"),
        description: label("Workspace file explorer."),
        icon: { kind: "lucide", name: "Folder" },
        location: "sidebar",
        allowMultiple: false,
        canBePinned: true,
      },
    ],
    components: [],
    workspaceModules: [
      {
        id: WORKSPACE_FILES_MODULE_ID,
        title: label("Workspace Files"),
        description: label("File explorer, editor, previewer, import, export, and file actions."),
        icon: { kind: "lucide", name: "Folder" },
        primaryViewId: WORKSPACE_FILES_PRIMARY_VIEW_ID,
        explorerViewId: WORKSPACE_FILES_EXPLORER_VIEW_ID,
        supportedLayouts: ["single", "left", "right", "split"],
        defaultLayout: "split",
        settingsSectionId: WORKSPACE_FILES_SETTINGS_SECTION_ID,
        capabilityProfiles: ["workspace.module.base", "workspace.module.read", "workspace.module.write"],
        capabilityPresetIds: ["workspace.module.writer"],
        actions: [
          { commandId: WORKSPACE_FILES_COMMAND_TOGGLE_EXPLORER_ID, role: "explorer", order: 10 },
          { commandId: WORKSPACE_FILES_COMMAND_NEW_FILE_ID, role: "explorer", order: 20 },
          { commandId: WORKSPACE_FILES_COMMAND_NEW_FOLDER_ID, role: "explorer", order: 30 },
          { commandId: WORKSPACE_FILES_COMMAND_VIEW_SPLIT_ID, role: "toolbar", order: 40 },
        ],
      },
    ],
    actionRail: [
      { id: WORKSPACE_FILES_RAIL_TOGGLE_EXPLORER_ID, title: label("File Explorer", "core.workspace-files.explorer"), icon: { kind: "lucide", name: "Folder" }, group: "workspace.primary", order: 10, target: { kind: "command", commandId: WORKSPACE_FILES_COMMAND_TOGGLE_EXPLORER_ID } },
      { id: WORKSPACE_FILES_RAIL_NEW_FILE_ID, title: label("New File"), icon: { kind: "lucide", name: "FilePlus" }, group: "workspace.primary", order: 20, target: { kind: "command", commandId: WORKSPACE_FILES_COMMAND_NEW_FILE_ID } },
      { id: WORKSPACE_FILES_RAIL_NEW_FOLDER_ID, title: label("New Folder"), icon: { kind: "lucide", name: "FolderPlus" }, group: "workspace.primary", order: 30, target: { kind: "command", commandId: WORKSPACE_FILES_COMMAND_NEW_FOLDER_ID } },
      { id: WORKSPACE_FILES_RAIL_OPEN_HOST_FILE_ID, title: label("Open Markdown File", "core.commands.open-host-file"), icon: { kind: "lucide", name: "FolderOpen" }, group: "workspace.primary", order: 40, target: { kind: "command", commandId: WORKSPACE_FILES_COMMAND_OPEN_HOST_FILE_ID } },
      { id: WORKSPACE_FILES_RAIL_DOWNLOAD_ID, title: label("Download Workspace", "core.commands.download-workspace"), icon: { kind: "lucide", name: "Download" }, group: "workspace.secondary", order: 20, target: { kind: "command", commandId: WORKSPACE_FILES_COMMAND_DOWNLOAD_WORKSPACE_ID } },
      { id: WORKSPACE_FILES_RAIL_IMPORT_MARKDOWN_ID, title: label("Import Markdown", "core.import-markdown.title"), icon: { kind: "lucide", name: "Upload" }, group: "workspace.secondary", order: 35, target: { kind: "command", commandId: WORKSPACE_FILES_COMMAND_IMPORT_MARKDOWN_ID } },
    ],
    settingsSections: [
      {
        id: WORKSPACE_FILES_SETTINGS_SECTION_ID,
        title: label("Workspace Files"),
        description: label("File explorer, editor, preview, import, and export settings."),
        order: 12,
        schemaPath: "manifest.settingsSchema",
      },
    ],
  },
  settingsSchema: {
    version: 1,
    title: label("Workspace Files"),
    description: label("Workspace file module settings."),
    sections: [],
    fields: [],
  },
};
