import { createEmptyThemePreset, type MarkdownWorkspaceThemeTokenMap, type ThemePreset } from "@mdwrk/theme-contract";
import { renderThemeBridgeCssVariables, renderThemeCssVariables } from "@mdwrk/ui-tokens/theme-map";
import type {
  ThemeStudioExportArtifacts,
  ThemeStudioMetadata,
  ThemeStudioPackageArtifact,
  ThemeStudioResolvedSettings,
} from "./types.js";

export function sanitizeThemeIdentifier(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "custom-theme";
}

export function sanitizePackageName(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) {
    return "@mdwrk/theme-custom-theme";
  }
  return trimmed
    .replace(/\s+/g, "-")
    .replace(/[^@a-z0-9._\/-]+/gi, "-")
    .replace(/--+/g, "-")
    .replace(/-+\//g, "/")
    .replace(/\/-+/g, "/");
}

export function buildThemePreset(metadata: ThemeStudioMetadata, tokens: MarkdownWorkspaceThemeTokenMap): ThemePreset {
  const preset = createEmptyThemePreset(sanitizeThemeIdentifier(metadata.themeId), metadata.themeName.trim() || "Custom Theme");
  return {
    ...preset,
    metadata: {
      ...preset.metadata,
      name: metadata.themeName.trim() || "Custom Theme",
      description: metadata.description.trim() || undefined,
      author: metadata.author.trim() || undefined,
      version: "1.0.1",
    },
    tokens,
  };
}

export function createThemePackageArtifact(
  preset: ThemePreset,
  css: { readonly host: string; readonly renderer: string; readonly editor: string },
  metadata: ThemeStudioMetadata,
): ThemeStudioPackageArtifact {
  const packageName = sanitizePackageName(metadata.packageName);
  const themeId = sanitizeThemeIdentifier(preset.metadata.id);
  const packageJson = JSON.stringify({
    name: packageName,
    version: "0.1.0",
    type: "module",
    license: "Apache-2.0",
    description: preset.metadata.description ?? `Portable Markdown Workspace theme package for ${preset.metadata.name}.`,
    files: ["dist", "themes", "README.md"],
    style: "./dist/index.css",
    exports: {
      ".": "./dist/index.css",
      "./renderer.css": "./dist/renderer.css",
      "./editor.css": "./dist/editor.css",
      [`./themes/${themeId}.json`]: `./themes/${themeId}.json`,
    },
    keywords: ["markdown-workspace", "theme", "portable"],
  }, null, 2);

  const readme = [
    `# ${preset.metadata.name}`,
    "",
    preset.metadata.description ?? `Portable theme package scaffold generated by Theme Studio for ${preset.metadata.name}.`,
    "",
    "## Files",
    "",
    `- \`dist/index.css\` — host token CSS variables`,
    `- \`dist/renderer.css\` — renderer bridge CSS variables`,
    `- \`dist/editor.css\` — editor bridge CSS variables`,
    `- \`themes/${themeId}.json\` — theme preset JSON`,
  ].join("\n");

  const json = JSON.stringify(preset, null, 2);
  return {
    packageName,
    files: [
      { path: "package.json", content: packageJson, mimeType: "application/json" },
      { path: "README.md", content: readme, mimeType: "text/markdown" },
      { path: "dist/index.css", content: css.host, mimeType: "text/css" },
      { path: "dist/renderer.css", content: css.renderer, mimeType: "text/css" },
      { path: "dist/editor.css", content: css.editor, mimeType: "text/css" },
      { path: `themes/${themeId}.json`, content: json, mimeType: "application/json" },
    ],
  };
}

export function buildThemeStudioExports(
  metadata: ThemeStudioMetadata,
  tokens: MarkdownWorkspaceThemeTokenMap,
  settings: ThemeStudioResolvedSettings,
): ThemeStudioExportArtifacts {
  const preset = buildThemePreset(metadata, tokens);
  const compact = settings.compactCss;
  const hostCss = renderThemeCssVariables(tokens, { selector: ":root", compact });
  const rendererCss = renderThemeBridgeCssVariables("renderer", tokens, { selector: ":root", compact });
  const editorCss = renderThemeBridgeCssVariables("editor", tokens, { selector: ":root", compact });
  const packageArtifact = createThemePackageArtifact(preset, { host: hostCss, renderer: rendererCss, editor: editorCss }, metadata);

  return {
    preset,
    json: JSON.stringify(preset, null, 2),
    hostCss,
    rendererCss,
    editorCss,
    packageArtifact,
  };
}
