import type { ExtensionManifest } from "@mdwrk/extension-manifest";
import {
  GEMINI_AGENT_COMMAND_APPLY_DRAFT_TO_SELECTION_ID,
  GEMINI_AGENT_COMMAND_OPEN_ID,
  GEMINI_AGENT_COMMAND_REPLACE_DOCUMENT_WITH_DRAFT_ID,
  GEMINI_AGENT_COMMAND_REWRITE_SELECTION_ID,
  GEMINI_AGENT_COMMAND_SUMMARIZE_FILE_ID,
  GEMINI_AGENT_EXTENSION_ID,
  GEMINI_AGENT_RAIL_ID,
  GEMINI_AGENT_SETTINGS_SECTION_CONTEXT,
  GEMINI_AGENT_SETTINGS_SECTION_GENERAL,
  GEMINI_AGENT_SETTINGS_SECTION_WRITEBACK,
  GEMINI_AGENT_VIEW_ID,
} from "./constants.js";
import { geminiAgentLabels } from "./i18n.js";
import { GEMINI_AGENT_EXTENSION_VERSION } from "./version.js";

export const geminiAgentManifest: ExtensionManifest = {
  manifestVersion: 1,
  id: GEMINI_AGENT_EXTENSION_ID,
  packageName: "@mdwrk/extension-gemini-agent",
  version: GEMINI_AGENT_EXTENSION_VERSION,
  displayName: geminiAgentLabels.manifestDisplayName,
  description: geminiAgentLabels.manifestDescription,
  kind: "bundled",
  publisher: "Markdown Workspace",
  license: "Apache-2.0",
  categories: ["ai", "assistant", "workflow"],
  keywords: ["gemini", "assistant", "markdown", "rewrite", "summary"],
  icon: { kind: "lucide", name: "Bot" },
  enabledByDefault: true,
  capabilities: [
    "workspace.read",
    "editor.read",
    "editor.write",
    "selection.read",
    "settings.read",
    "settings.write",
    "notification.publish",
    "command.invoke",
    "actionRail.register",
    "view.register",
    "network.fetch"
  ],
  compatibility: {
    manifestVersion: 1,
    hostApi: "^1.0.0",
    runtime: "^1.0.0",
    app: ">=1.3.49",
    themeContract: "^1.0.0",
    renderer: "^1.0.0",
    editor: "^1.0.0",
  },
  entry: {
    module: "./createGeminiAgentBundledEntry.js",
    export: "createGeminiAgentBundledEntry",
  },
  contributions: {
    commands: [
      {
        id: GEMINI_AGENT_COMMAND_OPEN_ID,
        title: geminiAgentLabels.commandOpenTitle,
        description: geminiAgentLabels.commandOpenDescription,
        icon: { kind: "lucide", name: "Bot" },
        keywords: ["gemini", "agent", "assistant"],
      },
      {
        id: GEMINI_AGENT_COMMAND_SUMMARIZE_FILE_ID,
        title: geminiAgentLabels.commandSummarizeTitle,
        description: geminiAgentLabels.commandSummarizeDescription,
        icon: { kind: "lucide", name: "FileText" },
        keywords: ["gemini", "summary", "document", "markdown"],
      },
      {
        id: GEMINI_AGENT_COMMAND_REWRITE_SELECTION_ID,
        title: geminiAgentLabels.commandRewriteTitle,
        description: geminiAgentLabels.commandRewriteDescription,
        icon: { kind: "lucide", name: "Pencil" },
        keywords: ["gemini", "rewrite", "selection", "draft"],
      },
      {
        id: GEMINI_AGENT_COMMAND_APPLY_DRAFT_TO_SELECTION_ID,
        title: geminiAgentLabels.commandApplySelectionTitle,
        description: geminiAgentLabels.commandApplySelectionDescription,
        icon: { kind: "lucide", name: "Save" },
        keywords: ["gemini", "apply", "selection", "draft"],
      },
      {
        id: GEMINI_AGENT_COMMAND_REPLACE_DOCUMENT_WITH_DRAFT_ID,
        title: geminiAgentLabels.commandReplaceDocumentTitle,
        description: geminiAgentLabels.commandReplaceDocumentDescription,
        icon: { kind: "lucide", name: "Save" },
        keywords: ["gemini", "replace", "document", "draft"],
      },
    ],
    views: [
      {
        id: GEMINI_AGENT_VIEW_ID,
        title: geminiAgentLabels.viewTitle,
        description: geminiAgentLabels.viewDescription,
        icon: { kind: "lucide", name: "Bot" },
        location: "main",
        allowMultiple: false,
        canBePinned: true,
      },
    ],
    components: [],
    actionRail: [
      {
        id: GEMINI_AGENT_RAIL_ID,
        title: geminiAgentLabels.railTitle,
        icon: { kind: "lucide", name: "Bot" },
        group: "assistant",
        order: 10,
        target: {
          kind: "view",
          viewId: GEMINI_AGENT_VIEW_ID,
        },
      },
    ],
    settingsSections: [
      {
        id: `${GEMINI_AGENT_EXTENSION_ID}.settings`,
        title: geminiAgentLabels.settingsTitle,
        description: geminiAgentLabels.settingsDescription,
        order: 10,
        schemaPath: "manifest.settingsSchema",
      },
    ],
  },
  settingsSchema: {
    version: 1,
    title: geminiAgentLabels.settingsTitle,
    description: geminiAgentLabels.settingsDescription,
    sections: [
      {
        id: GEMINI_AGENT_SETTINGS_SECTION_GENERAL,
        title: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.sections.general.title`, defaultMessage: "Provider" },
        description: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.sections.general.description`, defaultMessage: "Configure the Gemini endpoint, model selection, authentication, and request behavior." },
      },
      {
        id: GEMINI_AGENT_SETTINGS_SECTION_CONTEXT,
        title: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.sections.context.title`, defaultMessage: "Context" },
        description: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.sections.context.description`, defaultMessage: "Control how the active document and current selection are attached to ad hoc prompts." },
      },
      {
        id: GEMINI_AGENT_SETTINGS_SECTION_WRITEBACK,
        title: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.sections.writeback.title`, defaultMessage: "Writeback" },
        description: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.sections.writeback.description`, defaultMessage: "Control whether Gemini drafts can be explicitly applied back into the editor." },
      },
    ],
    fields: [
      {
        key: "endpoint",
        kind: "string",
        sectionId: GEMINI_AGENT_SETTINGS_SECTION_GENERAL,
        label: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.endpoint.label`, defaultMessage: "API endpoint" },
        description: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.endpoint.description`, defaultMessage: "Base Gemini API endpoint or a full generateContent URL." },
        defaultValue: "https://generativelanguage.googleapis.com/v1beta",
        placeholder: "https://generativelanguage.googleapis.com/v1beta",
      },
      {
        key: "model",
        kind: "string",
        sectionId: GEMINI_AGENT_SETTINGS_SECTION_GENERAL,
        label: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.model.label`, defaultMessage: "Model" },
        description: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.model.description`, defaultMessage: "Gemini model name used for generateContent requests." },
        defaultValue: "gemini-2.5-flash",
      },
      {
        key: "authMode",
        kind: "select",
        sectionId: GEMINI_AGENT_SETTINGS_SECTION_GENERAL,
        label: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.authMode.label`, defaultMessage: "Authentication mode" },
        description: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.authMode.description`, defaultMessage: "Use an API key directly or route requests through an upstream that handles authentication." },
        defaultValue: "api-key",
        options: [
          {
            value: "api-key",
            label: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.authMode.option.apiKey`, defaultMessage: "API key" },
          },
          {
            value: "none",
            label: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.authMode.option.none`, defaultMessage: "No direct auth in extension" },
          },
        ],
      },
      {
        key: "apiKey",
        kind: "secret",
        sectionId: GEMINI_AGENT_SETTINGS_SECTION_GENERAL,
        label: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.apiKey.label`, defaultMessage: "API key" },
        description: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.apiKey.description`, defaultMessage: "Gemini API key used when authentication mode is set to API key." },
        defaultValue: "",
      },
      {
        key: "systemPrompt",
        kind: "string",
        sectionId: GEMINI_AGENT_SETTINGS_SECTION_GENERAL,
        label: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.systemPrompt.label`, defaultMessage: "System prompt" },
        description: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.systemPrompt.description`, defaultMessage: "Instruction prepended to every Gemini request." },
        defaultValue: "You are an expert markdown copilot. Preserve markdown structure unless the user explicitly asks for a format change.",
        multiline: true,
      },
      {
        key: "temperature",
        kind: "number",
        sectionId: GEMINI_AGENT_SETTINGS_SECTION_GENERAL,
        label: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.temperature.label`, defaultMessage: "Temperature" },
        description: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.temperature.description`, defaultMessage: "Sampling temperature passed to Gemini." },
        defaultValue: 0.2,
        min: 0,
        max: 2,
        step: 0.1,
      },
      {
        key: "requestTimeoutMs",
        kind: "integer",
        sectionId: GEMINI_AGENT_SETTINGS_SECTION_GENERAL,
        label: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.timeout.label`, defaultMessage: "Request timeout (ms)" },
        description: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.timeout.description`, defaultMessage: "Abort the Gemini request if it exceeds this duration." },
        defaultValue: 30000,
        min: 1000,
        max: 300000,
        step: 1000,
      },
      {
        key: "autoAttachDocument",
        kind: "boolean",
        sectionId: GEMINI_AGENT_SETTINGS_SECTION_CONTEXT,
        label: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.autoAttachDocument.label`, defaultMessage: "Attach active document to custom prompts" },
        description: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.autoAttachDocument.description`, defaultMessage: "Include the current markdown document when using the custom prompt workflow." },
        defaultValue: true,
      },
      {
        key: "autoAttachSelection",
        kind: "boolean",
        sectionId: GEMINI_AGENT_SETTINGS_SECTION_CONTEXT,
        label: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.autoAttachSelection.label`, defaultMessage: "Attach current selection to custom prompts" },
        description: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.autoAttachSelection.description`, defaultMessage: "Include the current selection when using the custom prompt workflow." },
        defaultValue: true,
      },
      {
        key: "allowWriteBack",
        kind: "boolean",
        sectionId: GEMINI_AGENT_SETTINGS_SECTION_WRITEBACK,
        label: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.allowWriteBack.label`, defaultMessage: "Allow explicit writeback" },
        description: { key: `${GEMINI_AGENT_EXTENSION_ID}.settings.fields.allowWriteBack.description`, defaultMessage: "Permit the Apply actions to write Gemini drafts into the editor. Disabled by default for safety." },
        defaultValue: false,
      },
    ],
  },
  i18n: {
    defaultLocale: "en",
    supportedLocales: ["en", "es"],
  },
  distribution: {
    channel: "bundled",
    format: "esm",
  },
  support: {
    owner: "Markdown Workspace",
    status: "active",
    level: "official",
  },
};

export {
  GEMINI_AGENT_EXTENSION_ID,
  GEMINI_AGENT_VIEW_ID,
  GEMINI_AGENT_RAIL_ID,
  GEMINI_AGENT_COMMAND_OPEN_ID,
  GEMINI_AGENT_COMMAND_SUMMARIZE_FILE_ID,
  GEMINI_AGENT_COMMAND_REWRITE_SELECTION_ID,
  GEMINI_AGENT_COMMAND_APPLY_DRAFT_TO_SELECTION_ID,
  GEMINI_AGENT_COMMAND_REPLACE_DOCUMENT_WITH_DRAFT_ID,
};
