name: Docker Compose Restart (Client)

on:
  push:
    branches:
      - master
    paths:
      - client/**
      - docker-compose.yml
  workflow_dispatch:


concurrency:
  group: dist-docker-restart-clien
  cancel-in-progress: false

jobs:
  restart-client:
    runs-on: deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stop client container
        continue-on-error: true
        run: docker-compose stop client

      - name: Stop client container
        continue-on-error: true
        run: docker-compose rm -f client

      - name: Prune docker images
        continue-on-error: true
        run: docker system prune -af

      - name: Restart client container
        run: docker-compose up -d --build --force-recreate --no-deps client
