name: Lander Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: shortlived
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build lander
        run: npm run build:lander
